# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and e-mobility-driver-app contributors
# SPDX-License-Identifier: Apache-2.0

name: License compliance check

on:
  pull_request:
    branches: [main]

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: [self-hosted, solinas-ubuntu_22_04]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4
